[server]
secure = false
domain = "localhost"
base = "http://localhost:3000"
host = "127.0.0.1"
port = 3000

[frontend]
base = "http://localhost:3000"

[google]
client_id = ""
client_secret = ""

[secrets]
jwt = ""